name: brick_build_example

publish_to: none

version: 0.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brick_build:
    path: ../

dependency_overrides:
  xml: ^7.0.1
  smithy:
    path: ../../../../smithy
  smithy_aws:
    path: ../../../../smithy_aws
  brick_core:
    path: ../../brick_core
